### PR TITLE
m-4589 dont destroy metadata

### PR DESCRIPTION
**Pull request by rsimonton**
Two changes to the repo:

1. Add new attribute to `nft-tokens` schema, `needToRefreshMediaFiles`
2. Added mongo migration per this repo's README to "modify" (technically drop existing + create new) index to add `needToRefreshMediaFiles` to the existing `sentForMediaAt_1` index

### CODE REVIEW

**Comment by PavelDonskikh** [comment]
Summary:
1. pull requests into this repo on dev should go into the "dev" branch as all services, when deployed not from the main branch, source the schema from that "dev" branch.
image
When, deployed from the main branch, the trailing #dev gets removed.
2. this repo needs to be added a github action (i.e. deployment) to run the migrations. literally to execute 
"npm run migrate-mongo up".
3. there's a migration added in this PR:
migrations/20220527181654-NftTokens.ts
which contains an update to an index.
Let's imagine that we have the github action set up which would execute this file - there's probably still a missing logic. 
There's a new property being added "needToRefreshMediaFiles" and after talking to Reid turns out that this property needs to be added to all existing records. I think the migration file also needs to have this logic which adds the new property to all records.
4. there's also needs to be the github action on reverting a PR. When reverting, this action should execute "npm run migrate-mongo down" but only if the originating PR had any migrations. perhaps worth checking up how the migration is set up in github actions in this repo https://github.com/UniverseXYZ/UniverseApp-Backend
5. and even more uncertain thing - lets' say we have all the github actions setup, how would all other services automatically update the schema changes? currently the only way to trigger the schema update is to manually run deployment in all services where we need to apply the schema change 0__o
@boris-bonin @vikinatora

**Comment by rsimonton** [comment]
@PavelDonskikh Thank you for the feedback.  I wasn't sure if the migration was the correct place to include the setting/unsetting of the new field but do agree it makes sense.  I've added it.

**Comment by rsimonton** [comment]
> pull requests into this repo on dev should go into the "dev" branch as all services, when deployed not from the main branch, source the schema from that "dev" branch

@PavelDonskikh does this mean I should open a second PR into the `dev` branch or that this PR should be switched to use that branch as the base?

**Comment by PavelDonskikh** [comment]
> > pull requests into this repo on dev should go into the "dev" branch as all services, when deployed not from the main branch, source the schema from that "dev" branch

this PR should be switched to be pointed into "dev".
so that other services, when deployed, can source the latest version from this repo.

**Comment by vikinatora** [comment]
Please let me and @boris-bonin know when this is ready for final review

**Comment by rsimonton** [comment]
@PavelDonskikh done. How do we manage getting the changes merged to alpha and eventually prod?

**Comment by PavelDonskikh** [comment]
> @PavelDonskikh done. How do we manage getting the changes merged to alpha and eventually prod?

when the "dev" branch is ready for prod, the dev branch needs to be merged into main.
then we need to trigger re-build & re-deployment of all services where we need the new schema to apply.
yeah, this flow is kinda inconvenient, but i can't see a better way right now 0__o.

**Comment by rsimonton** [comment]
@PavelDonskikh @vikinatora @boris-bonin sirs I am not clear what the path forward here is.  This is one of four PRs that are all related and depend on the schema updates.  Given the above uncertainties called out by Paul do we want to just manage the DB updates manually for the time being?  Is that even possible?  

cc: @ilia-andr

**Comment by PavelDonskikh** [comment]
if all the PRs, including this one, are ready, I think the path can be:
- first merge this PR
- manually run the code from the migration file on the dev DB
- merge other services' PRs into the current sprint branches and deploy to dev.
- actually all services that may be using the models, that are changed in this PR, need to be redeployed (it's up to 14 services 0__o)

after it's determined that it works on dev,
- create and merge a PR from dev to main in this repo
- manually run the code from the migration file on alpha DB
- create and merge other services' PRs from sprint branches into main branch and deploy to alpha.
- redeploy to alpha all services which has been redeployed for dev

for prod:
- manually run the migrations code on prod DB
- run deployments on prod

these steps imply that we do not have github actions set up for this repo...
yeah that's quite a process to make changes to the scraper schema and services.

**Review by vikinatora — APPROVED** [review]

**Comment by vikinatora** [comment]
I'm ok with the dev flow. Let's try to do that. @rsimonton can you paste the links here to the other 3 PRs so we can merge them together?

**Comment by vikinatora** [comment]
cc: @boris-bonin @PavelDonskikh we just need to decide who's going to do the deployment part 😄

**Review by vikinatora — APPROVED** [review]

**Comment by rsimonton** [comment]
> I'm ok with the dev flow. Let's try to do that. @rsimonton can you paste the links here to the other 3 PRs so we can merge them together?

- https://github.com/UniverseXYZ/Universe-Datascraper-Metadata-Producer/pull/16
- https://github.com/UniverseXYZ/Universe-Datascraper-Metadata-Consumer/pull/14
- https://github.com/UniverseXYZ/Universe-Datascraper-MediaFiles-Producer/pull/15

@vikinatora

**Pull request merged**
